name: Package and Release Chrome Extension

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required for creating releases and uploading assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Commit Message
        id: check_message
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Get Version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Zip Extension Files
        if: contains(steps.check_message.outputs.COMMIT_MESSAGE, 'make-a-release')
        run: |
          mkdir -p dist
          zip -r dist/snipe-chrome-extension.zip . -x "*.git*" -x "dist/*" -x ".github/*"

      - name: Create GitHub Release
        if: contains(steps.check_message.outputs.COMMIT_MESSAGE, 'make-a-release')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Chrome Extension Release v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            dist/snipe-chrome-extension.zip#snipe-chrome-extension-v${{ steps.get_version.outputs.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}